"""Generate secrets without placing secret values in the canonical configuration."""

from __future__ import annotations

import hashlib
import secrets
import string
from pathlib import Path

SECRET_KEYS = (
    "GRAFANA_ADMIN_USER",
    "GRAFANA_ADMIN_PASSWORD",
    "GRAYLOG_PASSWORD_SECRET",
    "GRAYLOG_ROOT_PASSWORD_SHA2",
    "OPENSEARCH_INITIAL_ADMIN_PASSWORD",
    "MONGODB_ROOT_PASSWORD",
    "MONGODB_REPLICA_SET_KEY",
    "POSTGRES_PASSWORD",
)


def _password(length: int = 40) -> str:
    # URI-safe because MongoDB/OpenSearch credentials are used in connection URIs.
    alphabet = string.ascii_letters + string.digits + "_-"
    while True:
        value = "".join(secrets.choice(alphabet) for _ in range(length))
        if (
            any(char.islower() for char in value)
            and any(char.isupper() for char in value)
            and any(char.isdigit() for char in value)
            and any(char in "_-" for char in value)
        ):
            return value


def generate_secret_values() -> dict[str, str]:
    graylog_admin_password = _password()
    return {
        "GRAFANA_ADMIN_USER": "admin",
        "GRAFANA_ADMIN_PASSWORD": _password(),
        "GRAFANA_DATABASE_HOST": "",
        "GRAFANA_DATABASE_NAME": "grafana",
        "GRAFANA_DATABASE_USER": "grafana",
        "GRAYLOG_PASSWORD_SECRET": secrets.token_hex(48),
        "GRAYLOG_ROOT_PASSWORD_SHA2": hashlib.sha256(
            graylog_admin_password.encode("utf-8")
        ).hexdigest(),
        "OPENSEARCH_INITIAL_ADMIN_PASSWORD": _password(),
        "MONGODB_ROOT_PASSWORD": _password(),
        # MongoDB keyfiles accept 6-1024 characters from the base64 alphabet.
        # Hex stays inside that alphabet and avoids YAML/URI punctuation.
        "MONGODB_REPLICA_SET_KEY": secrets.token_hex(384),
        "POSTGRES_PASSWORD": _password(),
        "GRAYLOG_INITIAL_ADMIN_PASSWORD": graylog_admin_password,
    }


def write_secret_file(path: str | Path, *, force: bool = False) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not force:
        raise FileExistsError(f"Refusing to overwrite existing secret file: {target}")
    values = generate_secret_values()
    text = [
        "# Generated by owctl. Keep this file out of source control.",
        "# GRAYLOG_INITIAL_ADMIN_PASSWORD is the one-time human-readable admin password.",
    ]
    text.extend(f"{key}={value}" for key, value in values.items())
    target.write_text("\n".join(text) + "\n", encoding="utf-8")
    try:
        target.chmod(0o600)
    except OSError:
        pass
    return target
